services:
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    container_name: mariadb_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mysql:/var/lib/mysql

  apache_react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react_server
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - ./react:/var/www/Animaloop
      - ./react/conf/httpd:/etc/httpd
      - /home/haru25fuyu/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/haru25fuyu/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    command: /usr/sbin/httpd -DFOREGROUND
    restart: unless-stopped

  apache_go:
    build:
      context: .
      dockerfile: Dockerfile.go
    container_name: go_server
    ports:
      - "8080:80"
      - "8443:443"
      - "2223:22"
    volumes:
      - ./go:/var/www/Animaloop
      - ./go/conf/httpd:/etc/httpd
      - /home/haru25fuyu/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/haru25fuyu/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    command: /usr/sbin/httpd -DFOREGROUND
    restart: unless-stopped

  apache_lp:
    build:
      context: .
      dockerfile: Dockerfile.lp
    container_name: lp_server
    ports:
      - "8081:80"
      - "8444:443"
      - "2224:22"
    volumes:
      - ./lp:/var/www/Animaloop
      - ./lp/conf/httpd:/etc/httpd
      - /home/haru25fuyu/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - /home/haru25fuyu/.ssh/known_hosts:/root/.ssh/known_hosts:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
    command: /usr/sbin/httpd -DFOREGROUND
    restart: unless-stopped

