import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../tokens";

const inputBase = {
  width: "100%",
  backgroundColor: colors.neutral50,
  border: `1px solid ${colors.neutral300}`,
  color: semantic.textPrimary,
  fontSize: fontSize.sm,
  borderRadius: radius.lg,
  padding: spacing[3],
  outline: "none",
  boxSizing: "border-box" as const,
  fontFamily: "inherit",
};

export const s = {
  section: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[5],
    borderRadius: radius.xl,
    border: `1px solid ${semantic.borderDefault}`,
  },
  title: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    marginBottom: spacing[6],
    paddingBottom: spacing[2],
    borderBottom: `1px solid ${colors.neutral100}`,
  },
  body: { display: "flex", flexDirection: "column" as const, gap: spacing[5] },
  label: {
    display: "block",
    marginBottom: spacing[2],
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  required: { color: colors.danger },
  input: { ...inputBase },
  textarea: { ...inputBase, minHeight: 150, resize: "none" as const },
  errMsg: {
    fontSize: fontSize.xs,
    color: colors.danger,
    marginTop: spacing[1],
  },
  typeToggle: { display: "flex", gap: spacing[2], marginBottom: spacing[3] },
  typeBtn: (active: boolean) => ({
    flex: 1,
    padding: `${spacing[2]}px ${spacing[4]}px`,
    border: `1px solid ${active ? colors.info : semantic.borderDefault}`,
    borderRadius: radius.full,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    cursor: "pointer",
    backgroundColor: active ? colors.infoBg : "transparent",
    color: active ? colors.info : semantic.textSecondary,
  }),
  categorySelected: {
    padding: spacing[3],
    backgroundColor: colors.infoBg,
    border: `1px solid ${colors.info}`,
    borderRadius: radius.lg,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categorySelectedLabel: {
    fontSize: fontSize.xs,
    color: colors.info,
    fontWeight: fontWeight.bold,
    display: "block",
    marginBottom: 2,
  },
  categorySelectedName: {
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
  },
  categoryChangeBtn: {
    fontSize: fontSize.xs,
    color: semantic.textMuted,
    background: "none",
    border: "none",
    cursor: "pointer",
    textDecoration: "underline",
  },
  categoryEmpty: {
    padding: spacing[4],
    backgroundColor: colors.neutral50,
    border: `1px dashed ${semantic.borderDefault}`,
    borderRadius: radius.lg,
    textAlign: "center" as const,
    fontSize: fontSize.sm,
    color: semantic.textMuted,
  },
  categoryEmptyBtn: {
    color: colors.info,
    fontWeight: fontWeight.bold,
    background: "none",
    border: "none",
    cursor: "pointer",
    textDecoration: "underline",
  },
  quantityRow: { display: "flex", alignItems: "center", gap: spacing[4] },
  quantityInput: { ...inputBase, width: 80, textAlign: "right" as const },
  multiToggle: {
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
    cursor: "pointer",
  },
  multiLabel: { fontSize: fontSize.sm, color: semantic.textSecondary },
};
