import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../tokens";

export const s = {
  section: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[5],
    borderRadius: radius.xl,
    border: `1px solid ${semantic.borderDefault}`,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing[4],
  },
  label: {
    display: "block",
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  required: { color: colors.danger, marginLeft: spacing[1] },
  countBadge: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
    backgroundColor: colors.neutral100,
    padding: `${spacing[1]}px ${spacing[2]}px`,
    borderRadius: radius.md,
  },
  addBtn: (disabled: boolean) => ({
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: disabled ? semantic.textMuted : colors.info,
    backgroundColor: disabled ? "transparent" : colors.infoBg,
    padding: `${spacing[1]}px ${spacing[2]}px`,
    borderRadius: radius.sm,
    border: "none",
    cursor: disabled ? "not-allowed" : "pointer",
    opacity: disabled ? 0.5 : 1,
  }),
  errMsg: {
    fontSize: fontSize.sm,
    color: colors.danger,
    marginBottom: spacing[3],
    backgroundColor: colors.dangerBg,
    padding: spacing[3],
    borderRadius: radius.lg,
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
  },
  placeholder: { minHeight: 120 },
};
