import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../tokens";

export const s = {
  bar: {
    position: "fixed" as const,
    bottom: `calc(64px + ${spacing[4]}px)`,
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 200,
    backgroundColor: semantic.bgSurface,
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.xl,
    padding: `${spacing[3]}px ${spacing[5]}px`,
    display: "flex",
    alignItems: "center",
    gap: spacing[4],
    ...shadow.lg,
    whiteSpace: "nowrap" as const,
  },
  iconWrap: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.successBg,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mainText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  subText: { fontSize: fontSize.xs, color: semantic.textMuted, marginTop: 2 },
  viewCartBtn: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.primary600,
    background: "none",
    border: "none",
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  closeBtn: {
    color: semantic.textMuted,
    background: "none",
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
};
