import { colors, semantic, spacing, radius, fontSize, fontWeight, shadow } from "../../tokens";

export const s = {
page: { backgroundColor: semantic.bgPage, minHeight: "100vh" },
pointBar: (visible: boolean) => ({ position: "fixed" as const, top: 64, zIndex: 30, left: "50%", transform: "translateX(-50%)", transition: "all 0.3s", opacity: visible ? 1 : 0, pointerEvents: visible ? "auto" as const : "none" as const }),
pointBadge: { backgroundColor: colors.primary600, backdropFilter: "blur(4px)", color: colors.neutral0, padding: `${spacing[2]}px ${spacing[4]}px`, borderRadius: radius.full, display: "flex", alignItems: "center", gap: spacing[2], fontSize: fontSize.sm, border: `1px solid ${colors.primary500}` },
main: { width: "100%", maxWidth: 1400, margin: "0 auto", paddingTop: spacing[6], paddingLeft: spacing[4], paddingRight: spacing[4] },
layout: { display: "grid", gridTemplateColumns: "1fr", gap: spacing[8], alignItems: "start" },
sidebar: { display: "none", position: "sticky" as const, top: 96 },
filterCard: { backgroundColor: semantic.bgSurface, borderRadius: radius.xl, border: `1px solid ${semantic.borderDefault}`, padding: spacing[5] },
filterTitle: { fontWeight: fontWeight.bold, color: semantic.textPrimary, marginBottom: spacing[4], display: "flex", alignItems: "center", gap: spacing[2] },
filterItem: (active: boolean) => ({ fontSize: fontSize.sm, padding: `${spacing[2]}px`, borderRadius: radius.sm, cursor: "pointer", color: active ? colors.info : semantic.textSecondary, backgroundColor: active ? colors.infoBg : "transparent", fontWeight: active ? fontWeight.bold : fontWeight.normal }),
pointCard: { backgroundColor: semantic.bgSurface, border: `1px solid ${colors.successBg}`, borderRadius: radius.xl, padding: spacing[4], display: "flex", flexDirection: "column" as const, gap: spacing[3] },
pointCardInner: { display: "flex", alignItems: "center", gap: spacing[3] },
pointIconWrap: { width: 40, height: 40, borderRadius: radius.full, backgroundColor: colors.successBg, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
pointLabel: { fontSize: fontSize.xs, color: semantic.textMuted, fontWeight: fontWeight.medium },
pointValue: { color: colors.success, fontWeight: fontWeight.bold, fontSize: fontSize.xl, fontFamily: "monospace" },
grid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: spacing[3] },
card: { display: "flex", flexDirection: "column" as const, backgroundColor: semantic.bgSurface, borderRadius: radius.xl, border: `1px solid ${semantic.borderDefault}`, overflow: "hidden", textDecoration: "none", ...shadow.sm },
cardImgWrap: { position: "relative" as const, aspectRatio: "1" as const, backgroundColor: colors.neutral100 },
cardImg: { width: "100%", height: "100%", objectFit: "cover" as const },
sellerAvatar: { position: "absolute" as const, top: spacing[2], left: spacing[2], width: 32, height: 32, borderRadius: radius.full, border: `2px solid ${colors.neutral0}`, objectFit: "cover" as const, backgroundColor: colors.neutral200 },
likeBtn: { position: "absolute" as const, bottom: spacing[2], right: spacing[2] },
cardBody: { padding: spacing[3], flex: 1, display: "flex", flexDirection: "column" as const, gap: spacing[1] },
cardName: { fontSize: fontSize.sm, fontWeight: fontWeight.medium, color: semantic.textPrimary, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" as const },
cardPrice: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: semantic.textPrimary, marginTop: "auto" },
pointDiscount: { fontSize: fontSize.xs, fontWeight: fontWeight.bold, color: colors.success, backgroundColor: colors.successBg, padding: `1px ${spacing[2]}px`, borderRadius: radius.sm, border: `1px solid ${colors.successBg}`, display: "inline-block" },
pointDiscountGray: { fontSize: fontSize.xs, color: colors.success, backgroundColor: colors.neutral50, padding: `1px ${spacing[2]}px`, borderRadius: radius.sm, border: `1px solid ${semantic.borderDefault}` },
skeleton: { display: "flex", flexDirection: "column" as const, backgroundColor: semantic.bgSurface, borderRadius: radius.xl, border: `1px solid ${semantic.borderDefault}`, overflow: "hidden", animation: "pulse 2s infinite" },
skeletonImg: { position: "relative" as const, aspectRatio: "1" as const, backgroundColor: colors.neutral200 },
skeletonAvatarPlaceholder: { position: "absolute" as const, top: spacing[2], left: spacing[2], width: 32, height: 32, borderRadius: radius.full, backgroundColor: colors.neutral300, border: `2px solid ${colors.neutral0}` },
skeletonLikePlaceholder: { position: "absolute" as const, bottom: spacing[2], right: spacing[2], width: 28, height: 28, borderRadius: radius.full, backgroundColor: colors.neutral300 },
skeletonBody: { padding: spacing[3], display: "flex", flexDirection: "column" as const, gap: spacing[2] },
skeletonLine: (w: string) => ({ height: 14, backgroundColor: colors.neutral200, borderRadius: radius.sm, width: w }),
empty: { paddingTop: spacing[10] * 2, paddingBottom: spacing[10] * 2, textAlign: "center" as const, color: semantic.textMuted },
};
