import { colors, semantic, spacing, radius, fontSize, fontWeight, shadow } from "../../tokens";

export const s = {
page: { backgroundColor: colors.neutral0, minHeight: "100vh", paddingBottom: 128 },
loadingWrap: { display: "flex", flexDirection: "column" as const, alignItems: "center", justifyContent: "center", minHeight: "60vh", gap: spacing[4], color: semantic.textMuted },
loadingText: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
main: { maxWidth: 1200, margin: "0 auto", padding: `0 ${spacing[4]}px` },
grid: { display: "grid", gridTemplateColumns: "1fr", gap: 0 },
galleryWrap: { width: "100%", backgroundColor: colors.neutral50, overflow: "hidden" },
noImg: { width: "100%", aspectRatio: "1" as const, display: "flex", alignItems: "center", justifyContent: "center", color: semantic.textMuted, backgroundColor: colors.neutral200 },
infoWrap: { paddingLeft: spacing[4], paddingRight: spacing[4], paddingTop: spacing[6], paddingBottom: spacing[6], display: "flex", flexDirection: "column" as const, gap: spacing[4] },
titleArea: { borderBottom: `1px solid ${colors.neutral100}`, paddingBottom: spacing[6] },
name: { fontSize: fontSize["2xl"], fontWeight: fontWeight.bold, color: semantic.textPrimary, lineHeight: 1.3, marginBottom: spacing[4], wordBreak: "break-all" as const },
priceRow: { display: "flex", alignItems: "center", gap: spacing[4] },
price: { fontSize: fontSize["3xl"], fontWeight: fontWeight.bold, color: colors.accent500 },
shippingBadge: { fontSize: fontSize.sm, padding: `${spacing[1]}px ${spacing[2]}px`, backgroundColor: colors.neutral100, color: semantic.textSecondary, borderRadius: radius.sm },
pointDiscountUp: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.success, backgroundColor: colors.successBg, padding: `${spacing[1]}px ${spacing[3]}px`, borderRadius: radius.lg, border: `1px solid ${colors.successBg}` },
pointDiscountDefault: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.success, backgroundColor: colors.neutral50, padding: `${spacing[1]}px ${spacing[3]}px`, borderRadius: radius.lg, border: `1px solid ${semantic.borderDefault}` },
detailSection: { borderRadius: radius.xl, padding: spacing[4], backgroundColor: semantic.bgSurface },
detailTitle: { fontSize: fontSize.base, fontWeight: fontWeight.bold, color: semantic.textPrimary, marginBottom: spacing[3] },
detailGrid: { display: "grid", gridTemplateColumns: "1fr", gap: spacing[3], fontSize: fontSize.sm },
detailRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
detailLabel: { color: semantic.textMuted },
detailValue: { fontWeight: fontWeight.medium, color: semantic.textPrimary },
specsContainer: { display: "grid", gridTemplateColumns: "1fr", gap: spacing[3], fontSize: fontSize.sm, marginTop: spacing[4], padding: spacing[4], backgroundColor: colors.neutral50, borderRadius: radius.lg },
specsHeader: { fontWeight: fontWeight.bold, color: semantic.textMuted, fontSize: fontSize.xs, textTransform: "uppercase" as const, letterSpacing: "0.06em", paddingBottom: spacing[1], borderBottom: `1px solid ${semantic.borderDefault}` },
descSection: { borderRadius: radius.xl, padding: spacing[4], backgroundColor: semantic.bgSurface },
descText: { fontSize: fontSize.sm, color: semantic.textSecondary, whiteSpace: "pre-wrap" as const, lineHeight: 1.7, wordBreak: "break-all" as const },
sellerCard: { display: "flex", alignItems: "center", gap: spacing[4], border: `1px solid ${semantic.borderDefault}`, borderRadius: radius.xl, padding: spacing[4], backgroundColor: semantic.bgSurface, textDecoration: "none", ...shadow.sm },
sellerAvatar: { width: 48, height: 48, borderRadius: radius.full, objectFit: "cover" as const, flexShrink: 0 },
sellerName: { fontWeight: fontWeight.medium, fontSize: fontSize.base, color: semantic.textPrimary },
sellerSub: { fontSize: fontSize.xs, color: semantic.textMuted },
actionBtns: { display: "flex", gap: spacing[3] },
questionBtn: { flex: 1, backgroundColor: colors.neutral100, color: semantic.textPrimary, borderRadius: radius.xl, fontWeight: fontWeight.bold, padding: `${spacing[3]}px 0`, border: "none", cursor: "pointer" },
editBtn: { flex: 2, backgroundColor: colors.neutral800, color: colors.neutral0, borderRadius: radius.xl, fontWeight: fontWeight.bold, padding: `${spacing[3]}px 0`, border: "none", cursor: "pointer" },
buyBtn: { flex: 2, backgroundColor: colors.accent500, color: colors.neutral0, borderRadius: radius.xl, fontWeight: fontWeight.bold, padding: `${spacing[3]}px 0`, border: "none", cursor: "pointer" },
soldOutBtn: { flex: 2, backgroundColor: colors.neutral400, color: colors.neutral0, borderRadius: radius.xl, fontWeight: fontWeight.bold, padding: `${spacing[3]}px 0`, border: "none", cursor: "not-allowed" },
stickyFooter: { position: "fixed" as const, bottom: 0, left: 0, right: 0, backgroundColor: semantic.bgSurface, borderTop: `1px solid ${semantic.borderDefault}`, padding: `${spacing[3]}px ${spacing[4]}px`, paddingBottom: `calc(${spacing[3]}px + env(safe-area-inset-bottom))` },
};
