import { semantic } from "../tokens";
import { CSSProperties } from "react";

export const s: Record<string, CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  card: {
    backgroundColor: semantic.bgSurface,
    width: "100%",
    maxWidth: 448,
    borderRadius: 20,
    boxShadow: "0 8px 24px rgba(26,26,26,0.14)",
    overflow: "hidden",
  },
  successBanner: {
    padding: "32px 24px 24px",
    textAlign: "center",
    borderBottom: `1px solid ${semantic.borderDefault}`,
  },
  body: { padding: 24 },
  primaryBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    backgroundColor: "#1a1a1a",
    color: "#fff",
    fontWeight: 700,
    fontSize: 16,
    border: "none",
    cursor: "pointer",
    boxShadow: "0 4px 12px rgba(0,0,0,0.15)",
  },
  secondaryBtn: {
    width: "100%",
    height: 48,
    borderRadius: 12,
    border: `2px solid ${semantic.borderDefault}`,
    color: semantic.textSecondary,
    fontWeight: 700,
    background: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  linkBtn: {
    fontSize: 12,
    color: semantic.textSecondary,
    background: "none",
    border: "none",
    cursor: "pointer",
    textDecoration: "underline",
    textUnderlineOffset: 4,
  },
};
