import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../../tokens";

export const s = {
  page: {
    backgroundColor: semantic.bgPage,
    minHeight: "100vh",
    paddingBottom: 80,
  },
  header: {
    backgroundColor: semantic.bgSurface,
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
    borderBottom: `1px solid ${semantic.borderDefault}`,
  },
  headerInner: {
    maxWidth: 480,
    margin: "0 auto",
    padding: `0 ${spacing[4]}px`,
    display: "flex",
    alignItems: "center",
    gap: spacing[4],
    height: 56,
  },
  title: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  tabs: {
    display: "flex",
    borderBottom: `1px solid ${semantic.borderDefault}`,
    backgroundColor: semantic.bgSurface,
  },
  tab: (active: boolean) => ({
    flex: 1,
    padding: `${spacing[3]}px 0`,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: active ? colors.info : semantic.textMuted,
    background: "none",
    border: "none",
    cursor: "pointer",
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing[2],
  }),
  tabIndicator: {
    position: "absolute" as const,
    bottom: 0,
    left: spacing[4],
    right: spacing[4],
    height: 2,
    backgroundColor: colors.info,
    borderRadius: `${radius.full}px ${radius.full}px 0 0`,
  },
  badge: {
    position: "absolute" as const,
    top: -4,
    right: -8,
    width: 8,
    height: 8,
    backgroundColor: colors.danger,
    borderRadius: radius.full,
    border: `2px solid ${colors.neutral0}`,
  },
  list: {
    maxWidth: 480,
    margin: "0 auto",
    padding: spacing[4],
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing[3],
  },
  item: {
    display: "flex",
    gap: spacing[4],
    backgroundColor: semantic.bgSurface,
    borderRadius: radius.xl,
    border: `1px solid ${semantic.borderDefault}`,
    padding: spacing[4],
    textDecoration: "none",
    ...shadow.sm,
  },
  img: {
    width: 80,
    height: 80,
    borderRadius: radius.lg,
    objectFit: "cover" as const,
    flexShrink: 0,
    backgroundColor: colors.neutral100,
    border: `1px solid ${semantic.borderDefault}`,
  },
  info: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "space-between",
  },
  itemName: {
    fontWeight: fontWeight.bold,
    fontSize: fontSize.sm,
    color: semantic.textPrimary,
  },
  bottomRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  price: { fontWeight: fontWeight.bold, color: semantic.textPrimary },
  detailLink: {
    display: "flex",
    alignItems: "center",
    gap: spacing[1],
    fontSize: fontSize.xs,
    color: semantic.textMuted,
    backgroundColor: colors.neutral50,
    padding: `${spacing[1]}px ${spacing[2]}px`,
    borderRadius: radius.md,
  },
};
