import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../../tokens";

export const s = {
  page: {
    backgroundColor: semantic.bgPage,
    minHeight: "100vh",
    paddingBottom: 80,
  },
  header: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[4],
    display: "flex",
    alignItems: "center",
    gap: spacing[4],
    borderBottom: `1px solid ${semantic.borderDefault}`,
    position: "sticky" as const,
    top: 0,
    zIndex: 10,
  },
  title: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  grid: {
    maxWidth: 640,
    margin: "0 auto",
    padding: spacing[4],
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: spacing[3],
  },
  card: {
    backgroundColor: semantic.bgSurface,
    borderRadius: radius.lg,
    border: `1px solid ${semantic.borderDefault}`,
    overflow: "hidden",
    textDecoration: "none",
    ...shadow.sm,
  },
  img: {
    width: "100%",
    aspectRatio: "1" as const,
    objectFit: "cover" as const,
    backgroundColor: colors.primary50,
  },
  body: { padding: spacing[3] },
  name: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: semantic.textPrimary,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical" as const,
  },
  price: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: colors.primary700,
    marginTop: spacing[1],
  },
};
