import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../../tokens";

export const s = {
  page: {
    backgroundColor: semantic.bgPage,
    minHeight: "100vh",
    paddingBottom: 80,
  },
  profileArea: {
    backgroundColor: semantic.bgSurface,
    padding: `${spacing[6]}px ${spacing[4]}px ${spacing[8]}px`,
  },
  avatarWrap: {
    width: 64,
    height: 64,
    borderRadius: radius.full,
    backgroundColor: colors.neutral200,
    overflow: "hidden",
    border: `1px solid ${colors.neutral100}`,
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" as const },
  avatarPlaceholder: {
    width: "100%",
    height: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.neutral100,
    color: colors.neutral400,
  },
  userName: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  editLink: {
    fontSize: fontSize.xs,
    color: semantic.textMuted,
    textDecoration: "none",
  },
  statsRow: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: spacing[6],
    textAlign: "center" as const,
    borderTop: `1px solid ${colors.neutral100}`,
    paddingTop: spacing[4],
  },
  statItem: { flex: 1, borderRight: `1px solid ${colors.neutral100}` },
  statItemLast: { flex: 1 },
  statValue: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  statLabel: { fontSize: fontSize.xs, color: semantic.textMuted },
  sectionTitle: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
    marginBottom: spacing[2],
    marginLeft: spacing[1],
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: spacing[3] },
  statCard: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[4],
    borderRadius: radius.xl,
    border: `1px solid ${colors.neutral100}`,
    height: 96,
    display: "flex",
    flexDirection: "column" as const,
    justifyContent: "space-between",
    position: "relative" as const,
    overflow: "hidden",
    textDecoration: "none",
    ...shadow.sm,
  },
  statCardIconRow: {
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    position: "relative" as const,
    zIndex: 1,
  },
  statCardIconBg: (bg: string) => ({
    padding: 6,
    backgroundColor: bg,
    borderRadius: radius.sm,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  statCardValue: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    position: "relative" as const,
    zIndex: 1,
  },
  menuSection: {
    backgroundColor: semantic.bgSurface,
    borderRadius: radius.lg,
    border: `1px solid ${semantic.borderDefault}`,
    overflow: "hidden",
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing[4],
    borderBottom: `1px solid ${semantic.borderDefault}`,
    textDecoration: "none",
    color: semantic.textPrimary,
  },
  menuItemLeft: { display: "flex", alignItems: "center", gap: spacing[3] },
  menuItemLabel: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: semantic.textPrimary,
  },
  menuItemSub: {
    fontSize: fontSize.xs,
    color: semantic.textMuted,
    marginTop: 2,
  },
  logoutBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    padding: spacing[4],
    background: "none",
    border: "none",
    cursor: "pointer",
    color: colors.danger,
  },
  alertDanger: {
    display: "block",
    backgroundColor: colors.dangerBg,
    border: `1px solid ${colors.accent200}`,
    color: colors.danger,
    fontSize: fontSize.sm,
    padding: spacing[3],
    borderRadius: radius.md,
    textDecoration: "none",
  },
  alertWarning: {
    display: "block",
    backgroundColor: colors.warningBg,
    border: `1px solid ${colors.primary200}`,
    color: colors.warning,
    fontSize: fontSize.sm,
    padding: spacing[3],
    borderRadius: radius.md,
  },
  badge: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.neutral0,
    backgroundColor: colors.danger,
    padding: `2px ${spacing[2]}px`,
    borderRadius: radius.full,
    minWidth: 18,
    textAlign: "center" as const,
  },
  sectionBody: {},
};
