import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../../tokens";

export const s = {
  page: { backgroundColor: semantic.bgPage, minHeight: "100vh" },
  hero: {
    backgroundColor: semantic.bgSurface,
    padding: `${spacing[8]}px ${spacing[4]}px`,
    textAlign: "center" as const,
    borderBottom: `1px solid ${semantic.borderDefault}`,
  },
  avatarWrap: {
    position: "relative" as const,
    display: "inline-block",
    marginBottom: spacing[3],
  },
  avatar: {
    width: 128,
    height: 128,
    borderRadius: radius.full,
    border: `4px solid ${colors.neutral0}`,
    ...shadow.lg,
    objectFit: "cover" as const,
  },
  name: {
    fontSize: fontSize["2xl"],
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    marginBottom: spacing[1],
  },
  username: { color: semantic.textMuted, marginBottom: spacing[5] },
  editBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: spacing[2],
    padding: `${spacing[2]}px ${spacing[8]}px`,
    backgroundColor: colors.neutral0,
    border: `1px solid ${semantic.borderDefault}`,
    color: semantic.textPrimary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    borderRadius: radius.full,
    textDecoration: "none",
    ...shadow.sm,
  },
  body: {
    maxWidth: 640,
    margin: "0 auto",
    padding: spacing[6],
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing[6],
  },
  section: {
    backgroundColor: semantic.bgSurface,
    padding: `${spacing[4]}px ${spacing[6]}px`,
    borderRadius: radius.lg,
    ...shadow.sm,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
    textTransform: "uppercase" as const,
    letterSpacing: "0.1em",
    marginBottom: spacing[4],
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
  },
  infoBlock: {
    backgroundColor: colors.neutral50,
    borderRadius: radius.xl,
    padding: spacing[5],
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing[4],
  },
  infoRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing[4],
    borderTop: `1px solid ${colors.neutral100}`,
  },
  infoLabel: {
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
  },
  infoValue: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  privateRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing[4],
    borderRadius: radius.xl,
    border: `1px solid ${colors.neutral100}`,
    backgroundColor: colors.neutral50,
  },
  privateLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
  },
  privateValue: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: semantic.textPrimary,
  },
  changeLink: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.success,
    textDecoration: "none",
  },
  socialRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing[4],
  },
  socialLeft: { display: "flex", alignItems: "center", gap: spacing[3] },
  socialIconWrap: {
    padding: spacing[2],
    backgroundColor: colors.primary50,
    color: colors.primary600,
    borderRadius: radius.lg,
    display: "flex",
  },
  socialName: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  socialSub: { fontSize: fontSize.xs, color: semantic.textMuted },
  linkedBadge: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.success,
    backgroundColor: colors.successBg,
    padding: `${spacing[1]}px ${spacing[3]}px`,
    borderRadius: radius.full,
    border: `1px solid ${colors.successBg}`,
  },
  unlinkBtn: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: semantic.textMuted,
    backgroundColor: colors.neutral100,
    padding: `${spacing[1]}px ${spacing[3]}px`,
    borderRadius: radius.full,
    border: "none",
    cursor: "pointer",
  },
  logoutBtn: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.danger,
    background: "none",
    border: "none",
    cursor: "pointer",
    textDecoration: "underline",
  },
};
