import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../../tokens";

export const s = {
  page: { backgroundColor: semantic.bgPage, minHeight: "100vh" },
  body: {
    maxWidth: 400,
    margin: "0 auto",
    padding: spacing[6],
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing[5],
  },
  card: {
    backgroundColor: semantic.bgSurface,
    borderRadius: radius.xl,
    padding: spacing[6],
    border: `1px solid ${semantic.borderDefault}`,
  },
  title: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    marginBottom: spacing[5],
  },
  phoneInput: { display: "flex", gap: spacing[2] },
  input: {
    flex: 1,
    height: 44,
    paddingLeft: spacing[4],
    paddingRight: spacing[4],
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.md,
    fontSize: fontSize.base,
    color: semantic.textPrimary,
    outline: "none",
  },
  sendBtn: {
    height: 44,
    paddingLeft: spacing[4],
    paddingRight: spacing[4],
    backgroundColor: colors.primary500,
    color: colors.neutral0,
    border: "none",
    borderRadius: radius.md,
    fontWeight: fontWeight.bold,
    cursor: "pointer",
    whiteSpace: "nowrap" as const,
  },
  codeInput: {
    width: "100%",
    height: 56,
    textAlign: "center" as const,
    fontSize: fontSize.xl,
    letterSpacing: "0.3em",
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.md,
    outline: "none",
  },
  verifyBtn: {
    width: "100%",
    height: 48,
    backgroundColor: colors.primary500,
    color: colors.neutral0,
    border: "none",
    borderRadius: radius.lg,
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    cursor: "pointer",
  },
  hint: {
    fontSize: fontSize.xs,
    color: semantic.textMuted,
    textAlign: "center" as const,
  },
};
