import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../../../tokens";

export const s = {
  wrap: { display: "flex", flexDirection: "column" as const, gap: spacing[4] },
  section: {
    backgroundColor: semantic.bgSurface,
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.xl,
    padding: spacing[4],
  },
  sectionTitle: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: semantic.textSecondary,
    marginBottom: spacing[3],
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontSize: fontSize.sm,
    color: semantic.textSecondary,
    padding: `${spacing[1]}px 0`,
  },
  totalRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    paddingTop: spacing[2],
    borderTop: `1px solid ${colors.neutral300}`,
    fontWeight: fontWeight.bold,
  },
  totalLabel: { color: semantic.textPrimary },
  totalValue: { color: colors.primary600, fontSize: fontSize.lg },
  optionLabel: (selected: boolean) => ({
    display: "block",
    cursor: "pointer",
    borderRadius: radius.lg,
    border: `1px solid ${selected ? colors.primary500 : semantic.borderDefault}`,
    backgroundColor: selected ? colors.primary50 : "transparent",
    padding: spacing[3],
    transition: "all 0.1s",
  }),
  optionTitle: { fontWeight: fontWeight.medium, fontSize: fontSize.sm },
  optionSub: { fontSize: fontSize.xs, color: semantic.textMuted },
  cardOption: (selected: boolean) => ({
    display: "flex",
    alignItems: "center" as const,
    gap: spacing[3],
    cursor: "pointer",
    borderRadius: radius.lg,
    border: `1px solid ${selected ? colors.primary500 : semantic.borderDefault}`,
    backgroundColor: selected ? colors.primary50 : "transparent",
    padding: spacing[3],
  }),
  cardLabel: { fontSize: fontSize.sm, fontWeight: fontWeight.medium },
  cardSub: { fontSize: fontSize.xs, color: semantic.textMuted },
  emptyCard: {
    fontSize: fontSize.sm,
    color: semantic.textMuted,
    border: `1px dashed ${semantic.borderDefault}`,
    borderRadius: radius.md,
    padding: spacing[3],
    textAlign: "center" as const,
  },
  errMsg: {
    color: colors.danger,
    fontSize: fontSize.sm,
    textAlign: "center" as const,
    marginBottom: spacing[2],
  },
  payBtn: {
    width: "100%",
    borderRadius: radius.xl,
    padding: `${spacing[3]}px 0`,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.neutral0,
    border: "none",
    cursor: "pointer",
    backgroundColor: colors.primary500,
  },
  payBtnBusy: { backgroundColor: colors.neutral400, cursor: "not-allowed" },
  cancelArea: {
    marginTop: spacing[8],
    paddingTop: spacing[6],
    borderTop: `1px dashed ${semantic.borderDefault}`,
  },
};
