import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../tokens";

export const s = {
  page: { backgroundColor: semantic.bgPage, minHeight: "100vh" },
  wrap: { maxWidth: 600, margin: "0 auto", padding: spacing[6] },
  title: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    marginBottom: spacing[6],
  },
  formGroup: { marginBottom: spacing[4] },
  label: {
    display: "block",
    fontSize: fontSize.sm,
    fontWeight: fontWeight.medium,
    color: semantic.textPrimary,
    marginBottom: spacing[1],
  },
  input: {
    width: "100%",
    height: 44,
    paddingLeft: spacing[4],
    paddingRight: spacing[4],
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.md,
    fontSize: fontSize.base,
    color: semantic.textPrimary,
    outline: "none",
    boxSizing: "border-box" as const,
  },
  textarea: {
    width: "100%",
    minHeight: 160,
    padding: spacing[4],
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.md,
    fontSize: fontSize.base,
    color: semantic.textPrimary,
    outline: "none",
    resize: "vertical" as const,
    fontFamily: "inherit",
    boxSizing: "border-box" as const,
  },
  errMsg: {
    fontSize: fontSize.xs,
    color: colors.danger,
    marginTop: spacing[1],
  },
  submitBtn: {
    width: "100%",
    height: 44,
    backgroundColor: colors.primary500,
    color: colors.neutral0,
    border: "none",
    borderRadius: radius.md,
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
    cursor: "pointer",
  },
};
