import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../tokens";

export const s = {
  page: {
    backgroundColor: semantic.bgSurfaceAlt,
    minHeight: "100vh",
    paddingBottom: 80,
  },
  header: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[4],
    display: "flex",
    alignItems: "center",
    gap: spacing[4],
    borderBottom: `1px solid ${semantic.borderDefault}`,
  },
  title: {
    fontSize: fontSize["2xl"],
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
  },
  list: {
    maxWidth: 640,
    margin: "0 auto",
    padding: spacing[4],
    display: "flex",
    flexDirection: "column" as const,
    gap: spacing[3],
  },
  item: {
    display: "flex",
    gap: spacing[4],
    backgroundColor: semantic.bgSurface,
    borderRadius: radius.xl,
    border: `1px solid ${semantic.borderDefault}`,
    padding: spacing[4],
    textDecoration: "none",
    ...shadow.sm,
  },
  img: {
    width: 80,
    height: 80,
    borderRadius: radius.md,
    objectFit: "cover" as const,
    flexShrink: 0,
    backgroundColor: colors.neutral100,
  },
  info: { flex: 1, minWidth: 0 },
  name: {
    fontWeight: fontWeight.medium,
    fontSize: fontSize.sm,
    color: semantic.textPrimary,
    marginBottom: spacing[1],
  },
  date: { fontSize: fontSize.xs, color: semantic.textMuted },
  draftBadge: {
    display: "inline-flex",
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    backgroundColor: colors.neutral100,
    color: semantic.textMuted,
    padding: `2px ${spacing[2]}px`,
    borderRadius: radius.sm,
    marginTop: spacing[1],
  },
};
