import { colors, semantic, spacing, radius, fontSize, fontWeight, shadow } from "../tokens";

export const s = {
page: { backgroundColor: semantic.bgPage, minHeight: "100vh" },
hero: { backgroundColor: semantic.bgSurface, padding: `${spacing[8]}px ${spacing[4]}px ${spacing[6]}px`, textAlign: "center" as const, borderBottom: `1px solid ${semantic.borderDefault}` },
avatar: { width: 96, height: 96, borderRadius: radius.full, objectFit: "cover" as const, border: `3px solid ${semantic.borderDefault}`, margin: "0 auto", display: "block", marginBottom: spacing[3] },
name: { fontSize: fontSize.xl, fontWeight: fontWeight.bold, color: semantic.textPrimary },
username: { color: semantic.textMuted, marginTop: 2 },
statsRow: { display: "flex", justifyContent: "center", gap: spacing[8], marginTop: spacing[4] },
statItem: { textAlign: "center" as const },
statValue: { fontSize: fontSize.lg, fontWeight: fontWeight.bold, color: semantic.textPrimary },
statLabel: { fontSize: fontSize.xs, color: semantic.textMuted },
actionRow: { display: "flex", gap: spacing[3], marginTop: spacing[5], justifyContent: "center" },
followBtn: (following: boolean) => ({ padding: `${spacing[2]}px ${spacing[6]}px`, borderRadius: radius.full, fontWeight: fontWeight.bold, fontSize: fontSize.sm, cursor: "pointer", border: `1px solid ${following ? semantic.borderDefault : colors.primary500}`, backgroundColor: following ? semantic.bgSurface : colors.primary500, color: following ? semantic.textPrimary : colors.neutral0 }),
blockBtn: { padding: `${spacing[2]}px ${spacing[4]}px`, borderRadius: radius.full, fontWeight: fontWeight.bold, fontSize: fontSize.sm, cursor: "pointer", border: `1px solid ${semantic.borderDefault}`, backgroundColor: semantic.bgSurface, color: semantic.textSecondary },
body: { maxWidth: 640, margin: "0 auto", padding: spacing[4] },
sectionTitle: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: semantic.textMuted, marginBottom: spacing[3], marginTop: spacing[5] },
grid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: spacing[3] },
itemCard: { backgroundColor: semantic.bgSurface, borderRadius: radius.lg, border: `1px solid ${semantic.borderDefault}`, overflow: "hidden", textDecoration: "none", ...shadow.sm },
itemImg: { width: "100%", aspectRatio: "1" as const, objectFit: "cover" as const, backgroundColor: colors.neutral100 },
itemBody: { padding: spacing[2] },
itemName: { fontSize: fontSize.xs, color: semantic.textPrimary, overflow: "hidden", display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical" as const },
itemPrice: { fontSize: fontSize.sm, fontWeight: fontWeight.bold, color: colors.primary700, marginTop: 2 },
reviewItem: { display: "flex", gap: spacing[3], padding: `${spacing[3]}px 0`, borderBottom: `1px solid ${semantic.borderDefault}` },
reviewAvatar: { width: 36, height: 36, borderRadius: radius.full, objectFit: "cover" as const, flexShrink: 0 },
reviewName: { fontSize: fontSize.sm, fontWeight: fontWeight.medium, color: semantic.textPrimary },
reviewText: { fontSize: fontSize.sm, color: semantic.textSecondary, marginTop: 2 },
stars: { color: colors.primary400, fontSize: fontSize.xs },
};
