import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../tokens";

export const s = {
  overlay: {
    position: "fixed" as const,
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 50,
  },
  modal: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[6],
    borderRadius: radius.xl,
    width: "100%",
    maxWidth: 448,
    ...shadow.lg,
  },
  title: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    marginBottom: spacing[4],
  },
  section: {
    backgroundColor: semantic.bgSurface,
    padding: spacing[6],
    borderRadius: radius.lg,
    ...shadow.sm,
    marginBottom: spacing[3],
  },
  sectionTitle: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    borderBottom: `1px solid ${semantic.borderDefault}`,
    paddingBottom: spacing[2],
    marginBottom: spacing[2],
  },
  infoBlock: { marginBottom: spacing[4] },
  infoTitle: { fontWeight: fontWeight.medium },
  label: {
    display: "flex",
    alignItems: "center",
    gap: spacing[2],
    marginBottom: spacing[2],
    cursor: "pointer",
    fontSize: fontSize.base,
  },
  summaryText: { fontWeight: fontWeight.medium, marginBottom: spacing[4] },
  errMsg: {
    color: colors.danger,
    fontSize: fontSize.sm,
    marginBottom: spacing[2],
  },
  submitBtn: {
    backgroundColor: colors.primary500,
    color: colors.neutral0,
    padding: `${spacing[2]}px ${spacing[4]}px`,
    borderRadius: radius.md,
    border: "none",
    cursor: "pointer",
    fontSize: fontSize.base,
  },
  cancelBtn: {
    marginTop: spacing[2],
    fontSize: fontSize.sm,
    color: semantic.textMuted,
    background: "none",
    border: "none",
    cursor: "pointer",
    textDecoration: "underline",
    display: "block",
  },
};
