import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
} from "../tokens";

export const s = {
  header: {
    backgroundColor: semantic.bgHeader,
    height: 100,
    width: "100%",
    position: "static" as const,
    top: 0,
    left: 0,
    alignItems: "center",
    borderBottom: `1px solid ${semantic.borderDefault}`,
  },
  category: {
    backgroundColor: colors.neutral900,
    padding: spacing[1],
    display: "flex",
  },
  categoryTitle: {
    color: colors.neutral0,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.base,
    margin: 0,
  },
  headerMenu: {
    display: "flex",
  },
  logo: {
    maxWidth: "20%",
    height: "auto",
    padding: 0,
    marginLeft: spacing[2],
  },
  menuTitle: {
    fontSize: fontSize.base,
    marginTop: spacing[1],
    marginLeft: spacing[1],
    marginRight: "auto",
  },
  headerList: {
    display: "inline-block",
    listStyle: "none",
    fontSize: 17,
    height: "100%",
    width: "100%",
    marginLeft: "2vw",
    marginTop: 0,
    marginBottom: 0,
    padding: 0,
  },
  rightMargin: {
    display: "flex",
    flexDirection: "column" as const,
    width: "50%",
  },
  searchForm: {
    display: "flex",
    padding: 1,
    backgroundColor: colors.neutral0,
    height: 30,
    width: "80%",
    marginLeft: "auto",
    marginTop: spacing[1],
    marginRight: spacing[2],
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.full,
  },
  searchInput: {
    width: "100%",
    height: "100%",
    padding: 0,
    border: "none",
    borderRadius: radius.full,
    backgroundColor: colors.neutral0,
    marginLeft: 7,
    fontSize: 20,
    outline: "none",
    color: semantic.textPrimary,
  },
  login: {
    display: "flex",
    marginRight: spacing[2],
    marginTop: 15,
    fontSize: 17,
    color: semantic.textPrimary,
    textDecoration: "none",
  },
  loginLink: {
    display: "flex",
    marginLeft: "auto",
    marginRight: spacing[2],
    textDecoration: "none",
    color: semantic.textPrimary,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: radius.full,
    objectFit: "cover" as const,
  },
  icon: {
    color: semantic.textMuted,
    width: 48,
    height: 48,
    borderRadius: radius.full,
  },
};
