import {
  colors,
  semantic,
  spacing,
  radius,
  fontSize,
  fontWeight,
  shadow,
} from "../tokens";

export const s = {
  wrap: {
    backgroundColor: semantic.bgSurface,
    border: `1px solid ${semantic.borderDefault}`,
    borderRadius: radius.xl,
    padding: spacing[4],
    display: "flex",
    gap: spacing[4],
    alignItems: "center",
    ...shadow.sm,
  },
  img: {
    width: 64,
    height: 64,
    borderRadius: radius.md,
    objectFit: "cover" as const,
    backgroundColor: colors.primary50,
    flexShrink: 0,
  },
  info: { flex: 1, minWidth: 0 },
  name: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: semantic.textPrimary,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  price: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.primary700,
    marginTop: spacing[1],
  },
  badge: {
    display: "inline-flex",
    alignItems: "center",
    gap: spacing[1],
    backgroundColor: colors.primary100,
    color: colors.primary800,
    fontSize: fontSize.xs,
    fontWeight: fontWeight.medium,
    padding: `2px ${spacing[2]}px`,
    borderRadius: radius.sm,
    marginTop: spacing[1],
  },
};
